name: deploy

on:
  push:
    branches:
      - master  # Set a branch to deploy

jobs:
  pages:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: false  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.79.1'
          # extended: true

      - name: Build
        run: hugo --minify

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public

      - name: Sync to Gitee
        uses: x-dr/sync-repo-to-gitee@master
        env:
          SSH_KEY: ${{ secrets.GITEE_KEY }}
        with:
          github-repo: "git@github.com:serverlesslife-cn/serverlesslife.git"
          gitee-repo: "git@gitee.com:serverlesslife/serverlesslife.git"   
          
  serverless:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6]
    
    steps:
    - uses: actions/checkout@v1
    
    - name: Generate .env
      run: |
        touch .env
        echo TENCENT_SECRET_ID=${{secrets.TENCENT_SECRET_ID}} >> .env
        echo TENCENT_SECRET_KEY=${{secrets.TENCENT_SECRET_KEY}} >> .env
    
    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: '0.79.1'

    - name: Build
      run: hugo --minify
      
    - name: Deploy
      uses: serverless/github-action@master
      with:
          args: deploy
      env:
         TZ: Asia/Shanghai
         GLOBAL_ACCELERATOR_NA: true
          
