name: deploy

on:
  push:
    branches:
      - master  # Set a branch to deploy

jobs:
  pages:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: false  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.79.1'
          # extended: true

      - name: Build
        run: hugo --minify

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          
      - name: Sync to CODING
        uses: serverlesslife-cn/sync-repo-to-coding@master
        env:
            # 在 GitHub Settings->Secrets 配置 CODING_PRIVATE_KEY
            SSH_PRIVATE_KEY: ${{ secrets.CODING_PRIVATE_KEY }}
        with:
            # 注意替换为你的 GitHub 源仓库地址
            github-repo: "git@github.com:serverlesslife-cn/serverlesslife.git"
            # 注意替换为你的 CODING 目标仓库地址
            coding-repo: "git@e.coding.net:donghui1/serverlesslife/serverlesslife.git"
