name: Sync Repo
on:
  schedule:
    - cron:  '0 16 * * *'

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - name: Sync to Gitee
      uses: x-dr/sync-repo-to-gitee@master
      env:
          SSH_KEY: ${{ secrets.GITEE_KEY }}
      with:
          github-repo: "git@github.com:serverlesslife-cn/serverlesslife.git"
          gitee-repo: "git@gitee.com:serverlesslife/serverlesslife.git"

