name: Sync Repo
on:
  schedule:
    - cron:  '0 16 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Sync to Gitee
      uses: x-dr/sync-repo-to-gitee@master
      env:
          SSH_KEY: ${{ secrets.GITEE_KEY }}
      with:
          github-repo: "git@github.com:serverlesslife-cn/serverlesslife.git"
          gitee-repo: "git@gitee.com:serverlesslife/serverlesslife.git"

    - name: Sync to CODING
      uses: serverlesslife-cn/sync-repo-to-coding@master
      env:
          # 在 GitHub Settings->Secrets 配置 CODING_PRIVATE_KEY
          SSH_PRIVATE_KEY: ${{ secrets.CODING_PRIVATE_KEY }}
      with:
          # 注意替换为你的 GitHub 源仓库地址
          github-repo: "git@github.com:serverlesslife-cn/serverlesslife.git"
          # 注意替换为你的 CODING 目标仓库地址
          coding-repo: "git@e.coding.net:donghui1/serverlesslife/serverlesslife.git"
